apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false

  - name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
